export const verbs = [
  {
    base_form: "be",
    past_simple: "was, were",
    past_participle: "been",
    translation: "бути",
  },
  {
    base_form: "bear",
    past_simple: "bore",
    past_participle: "born",
    translation: "Виношувати (родити)",
  },
  {
    base_form: "beat",
    past_simple: "beat",
    past_participle: "beaten",
    translation: "Бити",
  },
  {
    base_form: "become",
    past_simple: "became",
    past_participle: "become",
    translation: "Ставати",
  },
  {
    base_form: "begin",
    past_simple: "began",
    past_participle: "begun",
    translation: "Починати",
  },
  {
    base_form: "bite",
    past_simple: "bit",
    past_participle: "bitten",
    translation: "Кусати (ся)",
  },
  {
    base_form: "break",
    past_simple: "broke",
    past_participle: "broken",
    translation: "Ламати",
  },
  {
    base_form: "blow",
    past_simple: "blew",
    past_participle: "blown",
    translation: "Дути",
  },
  {
    base_form: "bring",
    past_simple: "brought",
    past_participle: "brought",
    translation: "Приносити",
  },
  {
    base_form: "build",
    past_simple: "built",
    past_participle: "built",
    translation: "Будувати",
  },
  {
    base_form: "burn",
    past_simple: "burnt",
    past_participle: "burnt",
    translation: "Палити, горіти",
  },
  {
    base_form: "burst",
    past_simple: "burst",
    past_participle: "burst",
    translation: "Розбиватися, вибухати",
  },
  {
    base_form: "buy",
    past_simple: "bought",
    past_participle: "bought",
    translation: "Купляти",
  },
  {
    base_form: "catch",
    past_simple: "caught",
    past_participle: "caught",
    translation: "Ловити",
  },
  {
    base_form: "choose",
    past_simple: "chose",
    past_participle: "chosen",
    translation: "Вибирати",
  },
  {
    base_form: "come",
    past_simple: "came",
    past_participle: "come",
    translation: "Приходити",
  },
  {
    base_form: "cost",
    past_simple: "cost",
    past_participle: "cost",
    translation: "Коштувати",
  },
  {
    base_form: "cut",
    past_simple: "cut",
    past_participle: "cut",
    translation: "Різати",
  },
  {
    base_form: "dig",
    past_simple: "dug",
    past_participle: "dug",
    translation: "Копати",
  },
  {
    base_form: "do",
    past_simple: "did",
    past_participle: "done",
    translation: "Робити (виконувати)",
  },
  {
    base_form: "draw",
    past_simple: "drew",
    past_participle: "drawn",
    translation: "Малювати",
  },
  {
    base_form: "dream",
    past_simple: "dreamt",
    past_participle: "dreamt",
    translation: "Мріяти, бачити у сні",
  },
  {
    base_form: "drink",
    past_simple: "drank",
    past_participle: "drunk",
    translation: "Пити",
  },
  {
    base_form: "drive",
    past_simple: "drove",
    past_participle: "driven",
    translation: "Водити транспорт",
  },
  {
    base_form: "eat",
    past_simple: "ate",
    past_participle: "eaten",
    translation: "Їсти",
  },
  {
    base_form: "fall",
    past_simple: "fell",
    past_participle: "fallen",
    translation: "Падати",
  },
  {
    base_form: "feed",
    past_simple: "fed",
    past_participle: "fed",
    translation: "Годувати",
  },
  {
    base_form: "feel",
    past_simple: "felt",
    past_participle: "felt",
    translation: "Відчувати",
  },
  {
    base_form: "fight",
    past_simple: "fought",
    past_participle: "fought",
    translation: "Боротися",
  },
  {
    base_form: "find",
    past_simple: "found",
    past_participle: "found",
    translation: "Знаходити",
  },
  {
    base_form: "fly",
    past_simple: "flew",
    past_participle: "flown",
    translation: "Літати",
  },
  {
    base_form: "forget",
    past_simple: "forgot",
    past_participle: "forgotten",
    translation: "Забувати",
  },
  {
    base_form: "forgive",
    past_simple: "forgave",
    past_participle: "forgiven",
    translation: "Прощати",
  },
  {
    base_form: "freeze",
    past_simple: "froze",
    past_participle: "frozen",
    translation: "Заморожувати",
  },
  {
    base_form: "get",
    past_simple: "got",
    past_participle: "got",
    translation: "Отримувати (одержувати)",
  },
  {
    base_form: "give",
    past_simple: "gave",
    past_participle: "given",
    translation: "Давати",
  },
  {
    base_form: "go",
    past_simple: "went",
    past_participle: "gone",
    translation: "Йти, їхати",
  },
  {
    base_form: "grow",
    past_simple: "grew",
    past_participle: "grown",
    translation: "Рости",
  },
  {
    base_form: "hang",
    past_simple: "hung",
    past_participle: "hung",
    translation: "Висіти, повісити",
  },
  {
    base_form: "have",
    past_simple: "had",
    past_participle: "had",
    translation: "Мати щось",
  },
  {
    base_form: "hear",
    past_simple: "heard",
    past_participle: "heard",
    translation: "Чути",
  },
  {
    base_form: "hide",
    past_simple: "hid",
    past_participle: "hidden",
    translation: "Ховати (ся)",
  },
  {
    base_form: "hit",
    past_simple: "hit",
    past_participle: "hit",
    translation: "Ударяти",
  },
  {
    base_form: "hold",
    past_simple: "held",
    past_participle: "held",
    translation: "Тримати",
  },
  {
    base_form: "hurt",
    past_simple: "hurt",
    past_participle: "hurt",
    translation: "Ушкоджувати, боліти",
  },
  {
    base_form: "keep",
    past_simple: "kept",
    past_participle: "kept",
    translation: "Зберігати",
  },
  {
    base_form: "know",
    past_simple: "knew",
    past_participle: "known",
    translation: "Знати",
  },
  {
    base_form: "lay",
    past_simple: "laid",
    past_participle: "laid",
    translation: "Класти, покласти",
  },
  {
    base_form: "lead",
    past_simple: "led",
    past_participle: "led",
    translation: "Вести, водити",
  },
  {
    base_form: "learn",
    past_simple: "learnt",
    past_participle: "learnt",
    translation: "Вивчати",
  },
  {
    base_form: "lend",
    past_simple: "lent",
    past_participle: "lent",
    translation: "Позичати",
  },
  {
    base_form: "leave",
    past_simple: "left",
    past_participle: "left",
    translation: "Покидати",
  },
  {
    base_form: "let",
    past_simple: "let",
    past_participle: "let",
    translation: "Дозволяти",
  },
  {
    base_form: "lie",
    past_simple: "lay",
    past_participle: "lain",
    translation: "Лежати",
  },
  {
    base_form: "lose",
    past_simple: "lost",
    past_participle: "lost",
    translation: "Втрачати, губити",
  },
  {
    base_form: "make",
    past_simple: "made",
    past_participle: "made",
    translation: "Робити (виготовляти)",
  },
  {
    base_form: "mean",
    past_simple: "meant",
    past_participle: "meant",
    translation: "Означати",
  },
  {
    base_form: "meet",
    past_simple: "met",
    past_participle: "met",
    translation: "Зустрічати (ся)",
  },
  {
    base_form: "pay",
    past_simple: "paid",
    past_participle: "paid",
    translation: "Платити",
  },
  {
    base_form: "put",
    past_simple: "put",
    past_participle: "put",
    translation: "Класти",
  },
  {
    base_form: "read",
    past_simple: "read",
    past_participle: "read",
    translation: "Читати",
  },
  {
    base_form: "ride",
    past_simple: "rode",
    past_participle: "ridden",
    translation: "Їхати верхи",
  },
  {
    base_form: "ring",
    past_simple: "rang",
    past_participle: "rung",
    translation: "Дзвонити",
  },
  {
    base_form: "rise",
    past_simple: "rose",
    past_participle: "risen",
    translation: "Підніматися, вставати",
  },
  {
    base_form: "run",
    past_simple: "ran",
    past_participle: "run",
    translation: "Бігти",
  },
  {
    base_form: "say",
    past_simple: "said",
    past_participle: "said",
    translation: "Казати",
  },
  {
    base_form: "see",
    past_simple: "saw",
    past_participle: "seen",
    translation: "Бачити",
  },
  {
    base_form: "sell",
    past_simple: "sold",
    past_participle: "sold",
    translation: "Продавати",
  },
  {
    base_form: "send",
    past_simple: "sent",
    past_participle: "sent",
    translation: "Надсилати",
  },
  {
    base_form: "set",
    past_simple: "set",
    past_participle: "set",
    translation: "Установлювати",
  },
  {
    base_form: "shine",
    past_simple: "shone",
    past_participle: "shone",
    translation: "Світити",
  },
  {
    base_form: "shoot",
    past_simple: "shot",
    past_participle: "shot",
    translation: "Стріляти",
  },
  {
    base_form: "show",
    past_simple: "showed",
    past_participle: "shown",
    translation: "Показувати",
  },
  {
    base_form: "shut",
    past_simple: "shut",
    past_participle: "shut",
    translation: "Закривати",
  },
  {
    base_form: "sing",
    past_simple: "sang",
    past_participle: "sung",
    translation: "Співати",
  },
  {
    base_form: "sink",
    past_simple: "sank",
    past_participle: "sunk",
    translation: "Тонути",
  },
  {
    base_form: "sit",
    past_simple: "sat",
    past_participle: "sat",
    translation: "Сидіти",
  },
  {
    base_form: "sleep",
    past_simple: "slept",
    past_participle: "slept",
    translation: "Спати",
  },
  {
    base_form: "speak",
    past_simple: "spoke",
    past_participle: "spoken",
    translation: "Говорити",
  },
  {
    base_form: "spell",
    past_simple: "spelt",
    past_participle: "spelt",
    translation: "Писати по буквам",
  },
  {
    base_form: "spend",
    past_simple: "spent",
    past_participle: "spent",
    translation: "Проводити, витрачати",
  },
  {
    base_form: "stand",
    past_simple: "stood",
    past_participle: "stood",
    translation: "Стояти",
  },
  {
    base_form: "strike",
    past_simple: "struck",
    past_participle: "struck",
    translation: "Ударяти (ся)",
  },
  {
    base_form: "sweep",
    past_simple: "swept",
    past_participle: "swept",
    translation: "Замітати",
  },
  {
    base_form: "swim",
    past_simple: "swam",
    past_participle: "swum",
    translation: "Плавати",
  },
  {
    base_form: "take",
    past_simple: "took",
    past_participle: "taken",
    translation: "Брати",
  },
  {
    base_form: "teach",
    past_simple: "taught",
    past_participle: "taught",
    translation: "Вчити (когось)",
  },
  {
    base_form: "tell",
    past_simple: "told",
    past_participle: "told",
    translation: "Розповідати",
  },
  {
    base_form: "think",
    past_simple: "thought",
    past_participle: "thought",
    translation: "Думати",
  },
  {
    base_form: "throw",
    past_simple: "threw",
    past_participle: "thrown",
    translation: "Кидати",
  },
  {
    base_form: "understand",
    past_simple: "understood",
    past_participle: "understood",
    translation: "Розуміти",
  },
  {
    base_form: "wear",
    past_simple: "wore",
    past_participle: "worn",
    translation: "Носити (одяг)",
  },
  {
    base_form: "win",
    past_simple: "won",
    past_participle: "won",
    translation: "Перемагати",
  },
  {
    base_form: "write",
    past_simple: "wrote",
    past_participle: "written",
    translation: "Писати",
  },
  {
    base_form: "wake",
    past_simple: "woke",
    past_participle: "woken",
    translation: "Прокидатися",
  },
];
